    db:
      image: mysql:5.7
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      ports:
        - "3306:3306"
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        - "MYSQL_ROOT_PASSWORD=rootPass"
        - "MYSQL_USER=appuser"
        - "MYSQL_PASSWORD=userPass"
        - "MYSQL_DATABASE=app"
